### PR TITLE
Fix invalid character in page title

### LINKED ISSUE #143: crawler crashes if there is invalid character in page title
Crawler will crash if there is invalid charater in page title:
```

Crawling http://www1.umn.edu/humanrts/instree/n3ilo111.htm => http://hrlibrary.umn.edu/instree/n3ilo111.htm (200) html
 - Found title of: 'Discrimination (Employment and Occupation) Convention (ILO No. 111), 362 U.N.T.S. 31, <i>entered into force</i> June 15, 1960.'
 - External so stopping here.
Default exception handler: error/invalidpersistenterror Debug: title: Data submitted is invalid
Error code: invalidpersistenterror
$a contents: Data submitted is invalid
* line 528 of /lib/classes/persistent.php: core\invalid_persistent_exception thrown
* line 670 of /admin/tool/crawler/classes/robot/crawler.php: call to core\persistent->update()
* line 573 of /admin/tool/crawler/classes/robot/crawler.php: call to tool_crawler\robot\crawler->crawl()
* line 81 of /admin/tool/crawler/lib.php: call to tool_crawler\robot\crawler->process_queue()
* line 55 of /admin/tool/crawler/cli/crawler.php: call to tool_crawler_crawl()
```

### PR DESCRIPTION
**Pull request by tuanngocnguyen**
To fix #143

### CODE REVIEW

**Comment by tuanngocnguyen** [comment]
Hi @brendanheywood ,

I have created a patch for "Invalid character in page title", could you please have a look once you have some time? thanks

**Comment by brendanheywood** [comment]
@tuanngocnguyen the patch looks good, but can you please add a test around it

**Comment by tuanngocnguyen** [comment]
Hi @brendanheywood I have added unit test for the issue, would you please have another review once you have time? thanks

**Comment by brendanheywood** [comment]
awesome sauce

**Pull request merged**
