### PR TITLE
Update stored metainformation on recrawls

### PR DESCRIPTION
**Pull request by nicoroeser**
When crawling or scraping a resource for the n-th time (n>1), the metainformation which is stored in the database needs to be updated. This means especially the columns for document title, download error status and HTTP status-line.

This ensures correct display in reports, as well as a clean database. The former is important to users; the latter is convenient for developers when debugging the plugin.

### CODE REVIEW

**Comment by mattporritt** [comment]
Hi @nicoroeser,
Thanks for working on this patch. Your instances of:
` if (isset($row->errormsg) && !is_null($row->errormsg))`
could be replaced by `!empty` instead https://www.php.net/manual/en/function.empty.php

**Comment by nicoroeser** [comment]
Thanks for your comment, @mattporritt !

I had indeed briefly thought about using `!empty` when I prepared the patch; but I decided against it, mainly for two reasons:

1) It produces different results for some values, and thus is not a generic substitute. Relevant values here are:
 * `'0'` (string which contains only a DIGIT ZERO, U+0030): not a big problem because Curl should never return `CURLE_OK` (which equals `(int)0`) in case of an error. I wanted to make the code more robust in this case though.
 * `''` (the empty string): not relevant for now, but I wanted to prepare the code for possible future changes where the error message really is a string and not an integer. See the commit message of a39f5642d4d08ee33dd7addc911b6a25fc6a612b where I wrote: “"errormsg" purposefully is a column with type _text_: […]”.

Other possible values (we are talking about integers here which have been casted to string) return the same result for both possibilities.

2) It makes the code easier to understand (in my opinion): if you read `empty` in PHP, you _have to think_: ‘This is true if we have an empty string, or `null`, or `false`, or the string `'0'` (zero), or this or that.’ Then you have to find out what types the value may actually have, and whether all these values are likely to occur. The code _testing_ `$row->errormsg` is in another file, and in a totally different code path than the code _setting_ or storing the value of `errormsg`. This makes it more difficult for people reading the code to find it (but they will have to ensure that their search has returned _all_ occurrences of code setting this field/column anyway…).

If, in contrast, you read `isset($errormsg) && !is_null($errormsg)` then you think: ‘The error message is set and it is not `null`. So we have a real error message. (The opposite of having no error.)’ (At least that is how I would read that piece of code. Very verbose, I know.) I think that it makes the code better to use, more future-proof, and hardens it a bit more.

As you can see, both of my reasons are not caused by a necessity in _current_ code, but rather by the more general picture.

When I think about changing the code in the way you suggest, my gut feeling tells me to add a comment like `// Pay attention when changing this, the code reading this field expects a nonempty string which is not '0'.` to avoid future problems.

For **`httpmsg`**, the change can **not** be made, because it may be the empty string. The code proposed by me returns `true`, while `!empty('')` returns `false`. This would change the semantics of the code. It may be a good thing for the final reports – I haven’t looked into that –, but I tend to introduce smaller changes when possible, and separate such semantic changes from others, or to explain them in the commit message, for example.

**Comment by mattporritt** [comment]
Hi @nicoroeser,
Thanks for the explanation, I'm happy with this now.
(As an added bonus I also fixed travis checks)

**Comment by nicoroeser** [comment]
Thank you, @mattporritt , for merging, and for the added bonus!

**Pull request merged**
